/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as AuthenticatedProspeccaoRouteImport } from './routes/_authenticated/prospeccao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedDemonstrativosIndexRouteImport } from './routes/_authenticated/demonstrativos.index'
import { Route as AuthenticatedDemonstrativosIdRouteImport } from './routes/_authenticated/demonstrativos.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProspeccaoRoute = AuthenticatedProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemonstrativosIndexRoute =
  AuthenticatedDemonstrativosIndexRouteImport.update({
    id: '/demonstrativos/',
    path: '/demonstrativos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemonstrativosIdRoute =
  AuthenticatedDemonstrativosIdRouteImport.update({
    id: '/demonstrativos/$id',
    path: '/demonstrativos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/d/$slug': typeof DSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/demonstrativos/$id': typeof AuthenticatedDemonstrativosIdRoute
  '/demonstrativos/': typeof AuthenticatedDemonstrativosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/d/$slug': typeof DSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/demonstrativos/$id': typeof AuthenticatedDemonstrativosIdRoute
  '/demonstrativos': typeof AuthenticatedDemonstrativosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/prospeccao': typeof AuthenticatedProspeccaoRoute
  '/d/$slug': typeof DSlugRoute
  '/e/$slug': typeof ESlugRoute
  '/_authenticated/demonstrativos/$id': typeof AuthenticatedDemonstrativosIdRoute
  '/_authenticated/demonstrativos/': typeof AuthenticatedDemonstrativosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/prospeccao'
    | '/d/$slug'
    | '/e/$slug'
    | '/demonstrativos/$id'
    | '/demonstrativos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clientes'
    | '/dashboard'
    | '/prospeccao'
    | '/d/$slug'
    | '/e/$slug'
    | '/demonstrativos/$id'
    | '/demonstrativos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard'
    | '/_authenticated/prospeccao'
    | '/d/$slug'
    | '/e/$slug'
    | '/_authenticated/demonstrativos/$id'
    | '/_authenticated/demonstrativos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DSlugRoute: typeof DSlugRoute
  ESlugRoute: typeof ESlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/prospeccao': {
      id: '/_authenticated/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof AuthenticatedProspeccaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demonstrativos/': {
      id: '/_authenticated/demonstrativos/'
      path: '/demonstrativos'
      fullPath: '/demonstrativos/'
      preLoaderRoute: typeof AuthenticatedDemonstrativosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demonstrativos/$id': {
      id: '/_authenticated/demonstrativos/$id'
      path: '/demonstrativos/$id'
      fullPath: '/demonstrativos/$id'
      preLoaderRoute: typeof AuthenticatedDemonstrativosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProspeccaoRoute: typeof AuthenticatedProspeccaoRoute
  AuthenticatedDemonstrativosIdRoute: typeof AuthenticatedDemonstrativosIdRoute
  AuthenticatedDemonstrativosIndexRoute: typeof AuthenticatedDemonstrativosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProspeccaoRoute: AuthenticatedProspeccaoRoute,
  AuthenticatedDemonstrativosIdRoute: AuthenticatedDemonstrativosIdRoute,
  AuthenticatedDemonstrativosIndexRoute: AuthenticatedDemonstrativosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DSlugRoute: DSlugRoute,
  ESlugRoute: ESlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
